BOOKS = [
    {
        "id": 1,
        "title": "The Silent Cartographer",
        "author": "Meera Raghunathan",
        "genre": "Mystery",
        "year": 2018,
        "pages": 342,
        "price": 449.00,
        "rating": 4.3,
        "in_stock": True,
    },
    {
        "id": 2,
        "title": "Concrete and Monsoon",
        "author": "Arjun Balakrishnan",
        "genre": "Literary Fiction",
        "year": 2021,
        "pages": 288,
        "price": 399.00,
        "rating": 4.7,
        "in_stock": True,
    },
    {
        "id": 3,
        "title": "Ledgers of the Lost",
        "author": "Priya Nambiar",
        "genre": "Thriller",
        "year": 2020,
        "pages": 415,
        "price": 525.00,
        "rating": 3.9,
        "in_stock": False,
    },
    {
        "id": 4,
        "title": "A Short History of Longing",
        "author": "Devika Sen",
        "genre": "Non-fiction",
        "year": 2015,
        "pages": 512,
        "price": 699.00,
        "rating": 4.1,
        "in_stock": True,
    },
    {
        "id": 5,
        "title": "Iron Season",
        "author": "Kabir Malhotra",
        "genre": "Science Fiction",
        "year": 2023,
        "pages": 376,
        "price": 575.00,
        "rating": 4.5,
        "in_stock": True,
    },
    {
        "id": 6,
        "title": "The Understudy",
        "author": "Nikhil Fernandes",
        "genre": "Drama",
        "year": 2019,
        "pages": 244,
        "price": 349.00,
        "rating": 3.6,
        "in_stock": False,
    },
    {
        "id": 7,
        "title": "Salt Road",
        "author": "Anjali Verma",
        "genre": "Historical Fiction",
        "year": 2017,
        "pages": 468,
        "price": 599.00,
        "rating": 4.2,
        "in_stock": True,
    },
    {
        "id": 8,
        "title": "Debugging the Mind",
        "author": "Rohan Iyer",
        "genre": "Self-help",
        "year": 2022,
        "pages": 210,
        "price": 299.00,
        "rating": 3.4,
        "in_stock": True,
    },
    {
        "id": 9,
        "title": "Nine Rooms in Bandra",
        "author": "Farida Qureshi",
        "genre": "Literary Fiction",
        "year": 2024,
        "pages": 320,
        "price": 475.00,
        "rating": 4.8,
        "in_stock": True,
    },
    {
        "id": 10,
        "title": "The Last Analog Summer",
        "author": "Tanvi Deshpande",
        "genre": "Coming of Age",
        "year": 2016,
        "pages": 265,
        "price": 375.00,
        "rating": 4.0,
        "in_stock": False,
    },
]